name: Archive
on:
  workflow_dispatch:
  schedule:
    # Update every 6 hours, at quarter past to avoid top of hour load.
    - cron: '15 5,11,17,23 * * *'

jobs:
  build:
    permissions:
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - id: last-build
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10" 'https://api.github.com/repos/simonwo/lgposts/actions/artifacts' |
          jq '.artifacts.[] | select(.expired == false) | select(.size_in_bytes > 15000) | .workflow_run.id' | head -n1 | xargs printf 'run-id=%s' >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        if: ${{ steps.last-build.outputs.run-id != '' }}
        with:
          name: github-pages
          path: _site
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          run-id: ${{ steps.last-build.outputs.run-id }}

      - run: mkdir -p _site
        if: ${{ steps.last-build.outputs.run-id == '' }}

      - run: tar -xvf artifact.tar
        if: ${{ steps.last-build.outputs.run-id != '' }}
        working-directory: _site

      - run: bundle exec ruby archive.rb
        env:
          TUMBLR_SECRET_KEY: ${{ secrets.TUMBLR_SECRET_KEY }}
          TUMBLR_CLIENT_KEY: ${{ secrets.TUMBLR_CLIENT_KEY }}

      - name: Build index
        if: '!cancelled()'
        run: |
          find _site -name '*.json' ! -name 'index.json' |
          xargs jq '{"id": .id_string, "timestamp": .timestamp}' |
          jq -s 'sort_by(.timestamp)' > _site/index.json

      - uses: actions/upload-pages-artifact@v3.0.1
        if: '!cancelled()'
        with:
          path: _site

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
