name: Archive
on:
  schedule:
    # Update every 12 hours, at quarter past to avoid top of hour load.
    - cron: '15 11,23 * * *'
    # On Mondays, run additionally around likely update times.
    - cron: '15 12,13,14,15,21,22 * * 1'
    # On Tuesdays, run more often to catch notes in the first 48hrs.
    - cron: '15 0,3,7,15,19 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - run: mkdir _site
      - run: bundle exec ruby archive.rb
        env:
          TUMBLR_SECRET_KEY: ${{ secrets.TUMBLR_SECRET_KEY }}
          TUMBLR_CLIENT_KEY: ${{ secrets.TUMBLR_CLIENT_KEY }}
      - name: Build index
        if: '!cancelled()'
        run: |
          jq '{"id": .id_string, "timestamp": .timestamp}' _site/*.json | jq -s 'sort_by(.timestamp)' > _site/index.json
      - uses: actions/upload-pages-artifact@v3.0.1
        if: '!cancelled()'
        with:
          path: _site

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
